spring:
  application:
    name: payment-integration-service

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

  h2:
    console:
      enabled: true

core:
  outbox-dir: core-outbox